name: Build and Commit Docs
on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
          contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
    
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
    
            - name: Build documentation
              run: |
                python build.py
    
            - name: Commit and push changes
              uses: stefanzweifel/git-auto-commit-action@v6
              with:
                commit_message: "docs: Regenerate index.html and README.md"
                file_pattern: "index.html README.md"